### ISSUE TITLE
How to extract BLOBs

### ISSUE THREAD

**Issue by Circuit8** [pawlaszczyk/fqlite#10]
I have a corrupt database which has a load of data in the __FREELIST I want to access that are stored in BLOB columns. I can see its all there, when I copy and paste a single column I get the data correctly. However, when copying a whole row or the whole freelist it always truncates the BLOB data like so:

```CSV
[516, __FREELIST, 1060953, 13, F , 407293790, null, 262159, -0.17233276, 0.09866333, 0.01519260, [BLOB-0] 000010ba0000e039d3556739000030ba0000b039bab3ac39000038ba0000d039.., [BLOB-1] 0000e0ba0000883ac0188339007830be0010ca3d46c0f83c0000dfbb00007a3b.., [BLOB-2] 000000000000000000000000000080b8000000b90000c0b8000000b8000080b8..]
```

Is there anyway to extract the data preserving the BLOBS? My database has hundreds of rows so its not feasible to go through one by one

**Comment by Rasmus-Riis** [comment]
Have you tried fqlite or Sanderson?

Rasmus

**Comment by Circuit8** [comment]
@Rasmus-Riis This is FQLite isn't it? Sanderson seems to be a paid product.

**Comment by Rasmus-Riis** [comment]
Yes. That's the one. And yes. Sanderson is a paid product. 👍

**Comment by Circuit8** [comment]
I have tried FQLite, there is an issue with extracting blob data using it. Just thought I'd open an issue here to see if there's a solution?

**Comment by Rasmus-Riis** [comment]
Do that 🙂

**Comment by Circuit8** [comment]
Already done mate, you're in it.

**Comment by pawlaszczyk** [comment]
Hi Guys,
The issue will be answered in the next release. It will be possible to copy several lines - including complete BLOBs (by the end of next week - I'm on vacation right now.).

**Comment by pawlaszczyk** [comment]
The new release 2.7 is out now.  You can now choose between No BLOB export, Export BLOB to csv, Export BLOB to separate files. To enable one of this options just open the settings dialog. To start the export simply select the table, right-click on the table within the tree, choose export node...
