### ISSUE TITLE
Command line not working - GUI starts instead

### ISSUE THREAD

**Issue by markbaumgarten** [pawlaszczyk/fqlite#3]
When I run this:

java -jar fqlite_v1.5.5.jar nogui databases/com.google.android.apps.plus/databases/iu.upload.db

...the GUI starts.

I was hoping to get some CSV data instead... :-/

**Comment by pawlaszczyk** [comment]
Should work in fqlite 1.5.6. 
Background: In a runnable JAR-Archive there could be only one main() in the Manifest file. Solution: When using "nogui" option there is a redirect form GUI-class to the MAIN-class  (CLI).
