### ISSUE TITLE
Timestamps not displaying right time

### ISSUE THREAD

**Issue by thisislola** [pawlaszczyk/fqlite#4]
Hi, 

my database uses apple cocoa core times and this entry, in UTC, shoud be 22/10/2022 13:29 // 22/10/2022 13:30, yet the tool shows 03 instead. Is this an error in how it is translating the time? Thanks!

<img width="464" alt="image" src="https://user-images.githubusercontent.com/22214795/215752791-2e2045e6-149b-4aa1-867a-43115ef0e649.png">

**Comment by pawlaszczyk** [comment]
This should be fixed meanwhile.  The user interface displays UTC now and not the local time.
