### ISSUE TITLE
Package to .exe?

### ISSUE THREAD

**Issue by stark4n6** [pawlaszczyk/fqlite#5]
More of in inquiry than an issue. Is there any chance that the .jar could be packaged to an .exe for running?

**Comment by pawlaszczyk** [comment]
Hi, 
sorry for the late reply. 

In fact, there is now a version for Windows that is called via batch file. The new version of the tool 2.0 offers support for this. 

The latest Windows zip-archive is available form here 

https://www.staff.hs-mittweida.de/~pawlaszc/fqlite/downloads/FQlite.zip

(Note: This version is shipped with a JRE - you don't need to have a Java runtime environment installed).

There will be also a MacOSx64 and Linux version in the near future.

Kind Regards

Dirk

**Comment by stark4n6** [comment]
Awesome, thanks so much

**Comment by pawlaszczyk** [comment]
Hi,
I've finally managed to setup the newest version 2.1:

https://www.staff.hs-mittweida.de/~pawlaszc/fqlite/

It is not an ".exe" but a "run.bat" ;-)

Kind Regards

Dirk

**Comment by stark4n6** [comment]
Good enough, I actually just used this the other day, closing this request now, thanks!
