### ISSUE TITLE
Missing Data

### ISSUE THREAD

**Issue by stark4n6** [pawlaszczyk/fqlite#6]
I have noticed that FQLite is missing data when pulling in columns from tables. See pictures from DB Browser and FQLite

![image](https://github.com/pawlaszczyk/fqlite/assets/48143894/1c2f90b0-c720-4863-be72-efc5d3cb94ba)
DB Browser for SQLite

![image](https://github.com/pawlaszczyk/fqlite/assets/48143894/9d819400-bc73-4895-aaac-97d525c73371)
FQLite v2.6

If you'd like a sample of the database please let me know.

**Comment by pawlaszczyk** [comment]
Hi Kevin,
Looks like a silly bug. A example database would be helpful.

Kind Regards

Dirk

Prof. Dr. Dirk Pawlaszczyk

Studiendekan Master Cybercrime/Cybersecurity
Fakultät Angewandte Computer und Biowissenschaften
Hochschule Mittweida
University of Applied Sciences
Technikumplatz 17
09648 Mittweida

http://www.it-sicherheit-studieren.de<http://www.it-sicherheit-studieren.de/>
http://www.forensik-studieren.de<http://www.forensik-sutieren.de/>
http://www.cybercrime-studieren.de<http://www.cybercrime-studieren.de/>

Am 25.04.2024 um 15:32 schrieb Kevin - Stark 4N6 ***@***.***>:

﻿

I have noticed that FQLite is missing data when pulling in columns from tables. See pictures from DB Browser and FQLite

image.png (view on web)<https://github.com/pawlaszczyk/fqlite/assets/48143894/1c2f90b0-c720-4863-be72-efc5d3cb94ba>
DB Browser for SQLite

image.png (view on web)<https://github.com/pawlaszczyk/fqlite/assets/48143894/9d819400-bc73-4895-aaac-97d525c73371>
FQLite v2.6

If you'd like a sample of the database please let me know.

**Comment by stark4n6** [comment]
[wf_database.zip](https://github.com/pawlaszczyk/fqlite/files/15130868/wf_database.zip)

@pawlaszczyk Try this

**Comment by pawlaszczyk** [comment]
Thank you for sending. I've have fixed the problem. 

Background: The program searches for deleted tables. Several variants of the same table exist in this special database. The older version has only two columns. The table was probably extended at some point by an "ALTER TABLE" command. FQLite incorrectly used the old version. This problem has now been solved.

**Comment by stark4n6** [comment]
Thanks so much, will give it a try!
