### ISSUE TITLE
fqlite.descriptor.ADComparator, fqlite.util.Version and fqlite.base.BigByteBuffer cannot be resolved

### ISSUE THREAD

**Issue by froiloc** [pawlaszczyk/fqlite#9]
Hi,

Could you please add **fqlite.descriptor.ADComparator**, **fqlite.util.Version** and **fqlite.base.BigByteBuffer** to the git repo as well?

Thank you very much!

**Comment by pawlaszczyk** [comment]
Should work now. Updated repository.
